# Pandas DataFrames

In [1]:
import pandas as pd

In [2]:
# Creation of Dataframe using string
s = "hi hello gd evng".split()
pd.DataFrame(s)

       0
0     hi
1  hello
2     gd
3   evng

In [3]:
s1 = "how are you i am fyn".split()
pd.DataFrame(s1)

     0
0  how
1  are
2  you
3    i
4   am
5  fyn

In [4]:
# creation of dataframe using list
li = [[1,2,3],[4,5,6]]
pd.DataFrame(li)

   0  1  2
0  1  2  3
1  4  5  6

In [5]:
li1 = [[34,56,78],[56,77,89],[45,78,12]]
pd.DataFrame(li1)

    0   1   2
0  34  56  78
1  56  77  89
2  45  78  12

In [6]:
li2 = [[1,2,12],[56,78,90]]
pd.DataFrame(li2,index=['list1','list2'])

        0   1   2
list1   1   2  12
list2  56  78  90

In [7]:
# Creation of DataFrames using dictionary
d = {'key1':'h1','key2':'h2','key3':'h3','key4':'h4','key5':'h5'}
df1 = pd.DataFrame(d,index=[1,2,3,4,5])
df1

  key1 key2 key3 key4 key5
1   h1   h2   h3   h4   h5
2   h1   h2   h3   h4   h5
3   h1   h2   h3   h4   h5
4   h1   h2   h3   h4   h5
5   h1   h2   h3   h4   h5

In [4]:
import pandas as pd
d1 = {'name':['apssdc','oracle','python','datascience'],
      'rollno':[11,23,45,67],'Branch':['cse','ece','eee','civil']}
df = pd.DataFrame(d1)
df

          name  rollno Branch
0       apssdc      11    cse
1       oracle      23    ece
2       python      45    eee
3  datascience      67  civil

In [5]:
# creation of dataframe using tuple

In [6]:
df

          name  rollno Branch
0       apssdc      11    cse
1       oracle      23    ece
2       python      45    eee
3  datascience      67  civil

In [7]:
df.columns # to get only column names

Index(['name', 'rollno', 'Branch'], dtype='object')

In [8]:
df.values # to get row values

array([['apssdc', 11, 'cse'],
       ['oracle', 23, 'ece'],
       ['python', 45, 'eee'],
       ['datascience', 67, 'civil']], dtype=object)

In [9]:
# to get the number of records
print(len(df.values))

4

In [10]:
# to get the index positions
print(df.index)

RangeIndex(start=0, stop=4, step=1)

In [11]:
df

          name  rollno Branch
0       apssdc      11    cse
1       oracle      23    ece
2       python      45    eee
3  datascience      67  civil

In [12]:
print(df.shape)

(4, 3)

In [13]:
print(df['name'])

0         apssdc
1         oracle
2         python
3    datascience
Name: name, dtype: object

In [14]:
df['Branch']

0      cse
1      ece
2      eee
3    civil
Name: Branch, dtype: object

In [15]:
print(df[['rollno','Branch']])

   rollno Branch
0      11    cse
1      23    ece
2      45    eee
3      67  civil

In [16]:
# head() # to get 1st 5 records
df.head()

          name  rollno Branch
0       apssdc      11    cse
1       oracle      23    ece
2       python      45    eee
3  datascience      67  civil

In [17]:
# tail () # to get last 5 records
df.tail()

          name  rollno Branch
0       apssdc      11    cse
1       oracle      23    ece
2       python      45    eee
3  datascience      67  civil

In [18]:
df.head(1)

     name  rollno Branch
0  apssdc      11    cse

In [19]:
df.head(2)

     name  rollno Branch
0  apssdc      11    cse
1  oracle      23    ece

In [20]:
df.head(3)

     name  rollno Branch
0  apssdc      11    cse
1  oracle      23    ece
2  python      45    eee

In [21]:
df.tail(1)

          name  rollno Branch
3  datascience      67  civil

In [22]:
df.tail(2)

          name  rollno Branch
2       python      45    eee
3  datascience      67  civil

In [23]:
# to add new record to the dataframe
df.loc[4]=['java','7897','BBA']
print(df)

          name rollno Branch
0       apssdc     11    cse
1       oracle     23    ece
2       python     45    eee
3  datascience     67  civil
4         java   7897    BBA

In [24]:
# particular value update
df.loc[3,'Branch']='Arts'
df

          name rollno Branch
0       apssdc     11    cse
1       oracle     23    ece
2       python     45    eee
3  datascience     67   Arts
4         java   7897    BBA

In [25]:
# To get particular record details in dataframe
df.loc[2]

name      python
rollno        45
Branch       eee
Name: 2, dtype: object

In [26]:
df.loc[4]

name      java
rollno    7897
Branch     BBA
Name: 4, dtype: object

In [27]:
# to delete the rows and columns- drop()
# row wise - axis=0
# column wise - axis = 1
df

          name rollno Branch
0       apssdc     11    cse
1       oracle     23    ece
2       python     45    eee
3  datascience     67   Arts
4         java   7897    BBA

In [28]:
# particular row delete
df = df.drop(2,axis=0)
df

          name rollno Branch
0       apssdc     11    cse
1       oracle     23    ece
3  datascience     67   Arts
4         java   7897    BBA

In [29]:
# particular column delete
df = df.drop('Branch',axis=1)
df

          name rollno
0       apssdc     11
1       oracle     23
3  datascience     67
4         java   7897

In [30]:
# to print specific value
df.loc[3,'name']

'datascience'

In [31]:
# To rename the particular single column name
df.rename(columns={'rollno':'Rno'},inplace=True)
df

          name   Rno
0       apssdc    11
1       oracle    23
3  datascience    67
4         java  7897

In [32]:
# Rename multiple column names
df.columns=['NAME','ROLLNO']
df

          NAME ROLLNO
0       apssdc     11
1       oracle     23
3  datascience     67
4         java   7897

In [34]:
# to delete all row records
print(df)

          NAME ROLLNO
0       apssdc     11
1       oracle     23
3  datascience     67
4         java   7897

In [35]:
df.drop(df.index,inplace=True)
df

Empty DataFrame
Columns: [NAME, ROLLNO]
Index: []

In [36]:
# to delete entire columns
df.drop(df.columns,inplace=True,axis=1)
df

Empty DataFrame
Columns: []
Index: []

In [37]:
df

Empty DataFrame
Columns: []
Index: []