In [1]:
# import and load the data
import pandas as pd
df = pd.read_csv('employees.csv')
df

   ID   Name Department  Age  Salary       City
0   1   Ravi      Sales   28   45000      Delhi
1   2  Anita         HR   32   52000     Mumbai
2   3  Manoj         IT   25   60000  Hyderabad
3   4  Sneha      Sales   30   48000    Chennai
4   5  Kiran         IT   29   62000      Delhi
5   6  Pooja         HR   35   54000     Mumbai

In [4]:
# display the 1st 5 records
print(df.head())

   ID   Name Department  Age  Salary       City
0   1   Ravi      Sales   28   45000      Delhi
1   2  Anita         HR   32   52000     Mumbai
2   3  Manoj         IT   25   60000  Hyderabad
3   4  Sneha      Sales   30   48000    Chennai
4   5  Kiran         IT   29   62000      Delhi

In [5]:
# last 5 records
print(df.tail())

   ID   Name Department  Age  Salary       City
1   2  Anita         HR   32   52000     Mumbai
2   3  Manoj         IT   25   60000  Hyderabad
3   4  Sneha      Sales   30   48000    Chennai
4   5  Kiran         IT   29   62000      Delhi
5   6  Pooja         HR   35   54000     Mumbai

In [6]:
# print basic information
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          6 non-null      int64
 1   Name        6 non-null      object
 2   Department  6 non-null      object
 3   Age         6 non-null      int64
 4   Salary      6 non-null      int64
 5   City        6 non-null      object
dtypes: int64(3), object(3)
memory usage: 420.0+ bytes
None

In [7]:
# print statistical summary
print(df.describe())

             ID        Age        Salary
count  6.000000   6.000000      6.000000
mean   3.500000  29.833333  53500.000000
std    1.870829   3.430258   6625.707509
min    1.000000  25.000000  45000.000000
25%    2.250000  28.250000  49000.000000
50%    3.500000  29.500000  53000.000000
75%    4.750000  31.500000  58500.000000
max    6.000000  35.000000  62000.000000

In [2]:
# print unique departments
print(df['Department'].unique())

['Sales' 'HR' 'IT']

In [10]:
# to get no of rows and columns
df.shape

(6, 6)

In [11]:
# select one column
print(df['Name'])

0     Ravi
1    Anita
2    Manoj
3    Sneha
4    Kiran
5    Pooja
Name: Name, dtype: object

In [13]:
# select multiple column names
print(df[['Name','Salary']])

    Name  Salary
0   Ravi   45000
1  Anita   52000
2  Manoj   60000
3  Sneha   48000
4  Kiran   62000
5  Pooja   54000

In [16]:
# Employees in the IT Department
print(df[df['Department']=='IT'])

   ID   Name Department  Age  Salary       City
2   3  Manoj         IT   25   60000  Hyderabad
4   5  Kiran         IT   29   62000      Delhi

In [17]:
# Employees with salary>50000
print(df[df['Salary']>50000])

   ID   Name Department  Age  Salary       City
1   2  Anita         HR   32   52000     Mumbai
2   3  Manoj         IT   25   60000  Hyderabad
4   5  Kiran         IT   29   62000      Delhi
5   6  Pooja         HR   35   54000     Mumbai

In [27]:
# IT Employees in Delhi
print(df[(df['Department'] == 'IT') & (df['City'] == 'Delhi')])

   ID   Name Department  Age  Salary   City
4   5  Kiran         IT   29   62000  Delhi

In [28]:
# Sort by Salary
print(df.sort_values(by='Salary', ascending=False))

   ID   Name Department  Age  Salary       City
4   5  Kiran         IT   29   62000      Delhi
2   3  Manoj         IT   25   60000  Hyderabad
5   6  Pooja         HR   35   54000     Mumbai
1   2  Anita         HR   32   52000     Mumbai
3   4  Sneha      Sales   30   48000    Chennai
0   1   Ravi      Sales   28   45000      Delhi

In [29]:
# Sort by Age
print(df.sort_values(by='Age'))

   ID   Name Department  Age  Salary       City
2   3  Manoj         IT   25   60000  Hyderabad
0   1   Ravi      Sales   28   45000      Delhi
4   5  Kiran         IT   29   62000      Delhi
3   4  Sneha      Sales   30   48000    Chennai
1   2  Anita         HR   32   52000     Mumbai
5   6  Pooja         HR   35   54000     Mumbai

In [31]:
# Add new column for 10% salary increase
df['Updated_Salary'] = df['Salary'] * 1.10
df

   ID   Name Department  Age  Salary       City  Updated_Salary
0   1   Ravi      Sales   28   45000      Delhi         49500.0
1   2  Anita         HR   32   52000     Mumbai         57200.0
2   3  Manoj         IT   25   60000  Hyderabad         66000.0
3   4  Sneha      Sales   30   48000    Chennai         52800.0
4   5  Kiran         IT   29   62000      Delhi         68200.0
5   6  Pooja         HR   35   54000     Mumbai         59400.0

In [32]:
# Rename 'Department' to 'Dept'
df.rename(columns={'Department': 'Dept'}, inplace=True)

In [33]:
df

   ID   Name   Dept  Age  Salary       City  Updated_Salary
0   1   Ravi  Sales   28   45000      Delhi         49500.0
1   2  Anita     HR   32   52000     Mumbai         57200.0
2   3  Manoj     IT   25   60000  Hyderabad         66000.0
3   4  Sneha  Sales   30   48000    Chennai         52800.0
4   5  Kiran     IT   29   62000      Delhi         68200.0
5   6  Pooja     HR   35   54000     Mumbai         59400.0

In [34]:
# Average salary by department
print(df.groupby('Dept')['Salary'].mean())

Dept
HR       53000.0
IT       61000.0
Sales    46500.0
Name: Salary, dtype: float64

In [35]:
# Count employees per city
print(df['City'].value_counts())

City
Delhi        2
Mumbai       2
Hyderabad    1
Chennai      1
Name: count, dtype: int64

In [36]:
# Check for missing values
print(df.isnull().sum())

ID                0
Name              0
Dept              0
Age               0
Salary            0
City              0
Updated_Salary    0
dtype: int64

In [37]:
# Save to new CSV
df.to_csv("updated_employees.csv", index=False)
print("✅ File saved as updated_employees.csv")

✅ File saved as updated_employees.csv

In [4]:
# To read the data from a file/csv/xl
data = pd.read_csv('C:\\Users\\SIVA\\Documents\\Data_Analysis_workshop-PSMR\\IRIS.csv')
data

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
# to get how many no of rows and columns
data.shape

(150, 5)

In [6]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [7]:
# To change the column names 
data.columns=['V1','V2','V3','V4','Type']
data

      V1   V2   V3   V4            Type
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [8]:
# to get particular column details in csv file
data['Type']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Type, Length: 150, dtype: object

In [10]:
data['V1']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: V1, Length: 150, dtype: float64

In [11]:
data['Type'].value_counts()

Type
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [12]:
# to get the details of Iris-setosa
data[data['Type']=='Iris-setosa']

     V1   V2   V3   V4         Type
0   5.1  3.5  1.4  0.2  Iris-setosa
1   4.9  3.0  1.4  0.2  Iris-setosa
2   4.7  3.2  1.3  0.2  Iris-setosa
3   4.6  3.1  1.5  0.2  Iris-setosa
4   5.0  3.6  1.4  0.2  Iris-setosa
5   5.4  3.9  1.7  0.4  Iris-setosa
6   4.6  3.4  1.4  0.3  Iris-setosa
7   5.0  3.4  1.5  0.2  Iris-setosa
8   4.4  2.9  1.4  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
10  5.4  3.7  1.5  0.2  Iris-setosa
11  4.8  3.4  1.6  0.2  Iris-setosa
12  4.8  3.0  1.4  0.1  Iris-setosa
13  4.3  3.0  1.1  0.1  Iris-setosa
14  5.8  4.0  1.2  0.2  Iris-setosa
15  5.7  4.4  1.5  0.4  Iris-setosa
16  5.4  3.9  1.3  0.4  Iris-setosa
17  5.1  3.5  1.4  0.3  Iris-setosa
18  5.7  3.8  1.7  0.3  Iris-setosa
19  5.1  3.8  1.5  0.3  Iris-setosa
20  5.4  3.4  1.7  0.2  Iris-setosa
21  5.1  3.7  1.5  0.4  Iris-setosa
22  4.6  3.6  1.0  0.2  Iris-setosa
23  5.1  3.3  1.7  0.5  Iris-setosa
24  4.8  3.4  1.9  0.2  Iris-setosa
25  5.0  3.0  1.6  0.2  Iris-setosa
26  5.0  3.4  1.6  0.4  Iris-setosa
27  5.2  3.5  1.5  0.2  Iris-setosa
28  5.2  3.4  1.4  0.2  Iris-setosa
29  4.7  3.2  1.6  0.2  Iris-setosa
30  4.8  3.1  1.6  0.2  Iris-setosa
31  5.4  3.4  1.5  0.4  Iris-setosa
32  5.2  4.1  1.5  0.1  Iris-setosa
33  5.5  4.2  1.4  0.2  Iris-setosa
34  4.9  3.1  1.5  0.1  Iris-setosa
35  5.0  3.2  1.2  0.2  Iris-setosa
36  5.5  3.5  1.3  0.2  Iris-setosa
37  4.9  3.1  1.5  0.1  Iris-setosa
38  4.4  3.0  1.3  0.2  Iris-setosa
39  5.1  3.4  1.5  0.2  Iris-setosa
40  5.0  3.5  1.3  0.3  Iris-setosa
41  4.5  2.3  1.3  0.3  Iris-setosa
42  4.4  3.2  1.3  0.2  Iris-setosa
43  5.0  3.5  1.6  0.6  Iris-setosa
44  5.1  3.8  1.9  0.4  Iris-setosa
45  4.8  3.0  1.4  0.3  Iris-setosa
46  5.1  3.8  1.6  0.2  Iris-setosa
47  4.6  3.2  1.4  0.2  Iris-setosa
48  5.3  3.7  1.5  0.2  Iris-setosa
49  5.0  3.3  1.4  0.2  Iris-setosa

In [13]:
# head()
data.head()

    V1   V2   V3   V4         Type
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [14]:
data.tail()

      V1   V2   V3   V4            Type
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [17]:
# to add new column to the dataset
data['Type_len']=data['Type'].str.len()
data

      V1   V2   V3   V4            Type  Type_len
0    5.1  3.5  1.4  0.2     Iris-setosa        11
1    4.9  3.0  1.4  0.2     Iris-setosa        11
2    4.7  3.2  1.3  0.2     Iris-setosa        11
3    4.6  3.1  1.5  0.2     Iris-setosa        11
4    5.0  3.6  1.4  0.2     Iris-setosa        11
..   ...  ...  ...  ...             ...       ...
145  6.7  3.0  5.2  2.3  Iris-virginica        14
146  6.3  2.5  5.0  1.9  Iris-virginica        14
147  6.5  3.0  5.2  2.0  Iris-virginica        14
148  6.2  3.4  5.4  2.3  Iris-virginica        14
149  5.9  3.0  5.1  1.8  Iris-virginica        14

[150 rows x 6 columns]

In [18]:
data.columns

Index(['V1', 'V2', 'V3', 'V4', 'Type', 'Type_len'], dtype='object')

In [19]:
data.describe()

               V1          V2          V3          V4    Type_len
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667   13.333333
std      0.828066    0.433594    1.764420    0.763161    1.705367
min      4.300000    2.000000    1.000000    0.100000   11.000000
25%      5.100000    2.800000    1.600000    0.300000   11.000000
50%      5.800000    3.000000    4.350000    1.300000   14.000000
75%      6.400000    3.300000    5.100000    1.800000   15.000000
max      7.900000    4.400000    6.900000    2.500000   15.000000

In [20]:
# to print 2 or 3 columns at a time 
data[['V1','Type']]

      V1            Type
0    5.1     Iris-setosa
1    4.9     Iris-setosa
2    4.7     Iris-setosa
3    4.6     Iris-setosa
4    5.0     Iris-setosa
..   ...             ...
145  6.7  Iris-virginica
146  6.3  Iris-virginica
147  6.5  Iris-virginica
148  6.2  Iris-virginica
149  5.9  Iris-virginica

[150 rows x 2 columns]

In [21]:
data.count()

V1          150
V2          150
V3          150
V4          150
Type        150
Type_len    150
dtype: int64

In [22]:
data['V1'].min()

4.3

In [23]:
data['V1'].max()

7.9

In [24]:
# print v1 values between range
data[data['V1']>=5 & (data['V1']<=6)]

      V1   V2   V3   V4            Type  Type_len
0    5.1  3.5  1.4  0.2     Iris-setosa        11
1    4.9  3.0  1.4  0.2     Iris-setosa        11
2    4.7  3.2  1.3  0.2     Iris-setosa        11
3    4.6  3.1  1.5  0.2     Iris-setosa        11
4    5.0  3.6  1.4  0.2     Iris-setosa        11
..   ...  ...  ...  ...             ...       ...
145  6.7  3.0  5.2  2.3  Iris-virginica        14
146  6.3  2.5  5.0  1.9  Iris-virginica        14
147  6.5  3.0  5.2  2.0  Iris-virginica        14
148  6.2  3.4  5.4  2.3  Iris-virginica        14
149  5.9  3.0  5.1  1.8  Iris-virginica        14

[150 rows x 6 columns]

In [25]:
# To print only satosa and virginica
data[(data['Type']=='Iris-setosa') | (data['Type']=='Iris-virginica')]
data

      V1   V2   V3   V4            Type  Type_len
0    5.1  3.5  1.4  0.2     Iris-setosa        11
1    4.9  3.0  1.4  0.2     Iris-setosa        11
2    4.7  3.2  1.3  0.2     Iris-setosa        11
3    4.6  3.1  1.5  0.2     Iris-setosa        11
4    5.0  3.6  1.4  0.2     Iris-setosa        11
..   ...  ...  ...  ...             ...       ...
145  6.7  3.0  5.2  2.3  Iris-virginica        14
146  6.3  2.5  5.0  1.9  Iris-virginica        14
147  6.5  3.0  5.2  2.0  Iris-virginica        14
148  6.2  3.4  5.4  2.3  Iris-virginica        14
149  5.9  3.0  5.1  1.8  Iris-virginica        14

[150 rows x 6 columns]

In [26]:
# howmany types
data['Type'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [27]:
data.sort_index(axis=0)

      V1   V2   V3   V4            Type  Type_len
0    5.1  3.5  1.4  0.2     Iris-setosa        11
1    4.9  3.0  1.4  0.2     Iris-setosa        11
2    4.7  3.2  1.3  0.2     Iris-setosa        11
3    4.6  3.1  1.5  0.2     Iris-setosa        11
4    5.0  3.6  1.4  0.2     Iris-setosa        11
..   ...  ...  ...  ...             ...       ...
145  6.7  3.0  5.2  2.3  Iris-virginica        14
146  6.3  2.5  5.0  1.9  Iris-virginica        14
147  6.5  3.0  5.2  2.0  Iris-virginica        14
148  6.2  3.4  5.4  2.3  Iris-virginica        14
149  5.9  3.0  5.1  1.8  Iris-virginica        14

[150 rows x 6 columns]

In [28]:
# particular column sorting
data.sort_values('V3') # Ascending order

      V1   V2   V3   V4            Type  Type_len
22   4.6  3.6  1.0  0.2     Iris-setosa        11
13   4.3  3.0  1.1  0.1     Iris-setosa        11
14   5.8  4.0  1.2  0.2     Iris-setosa        11
35   5.0  3.2  1.2  0.2     Iris-setosa        11
36   5.5  3.5  1.3  0.2     Iris-setosa        11
..   ...  ...  ...  ...             ...       ...
131  7.9  3.8  6.4  2.0  Iris-virginica        14
105  7.6  3.0  6.6  2.1  Iris-virginica        14
117  7.7  3.8  6.7  2.2  Iris-virginica        14
122  7.7  2.8  6.7  2.0  Iris-virginica        14
118  7.7  2.6  6.9  2.3  Iris-virginica        14

[150 rows x 6 columns]

In [29]:
# decending order
data.sort_values('V1',ascending=False)

      V1   V2   V3   V4            Type  Type_len
131  7.9  3.8  6.4  2.0  Iris-virginica        14
135  7.7  3.0  6.1  2.3  Iris-virginica        14
122  7.7  2.8  6.7  2.0  Iris-virginica        14
117  7.7  3.8  6.7  2.2  Iris-virginica        14
118  7.7  2.6  6.9  2.3  Iris-virginica        14
..   ...  ...  ...  ...             ...       ...
41   4.5  2.3  1.3  0.3     Iris-setosa        11
42   4.4  3.2  1.3  0.2     Iris-setosa        11
38   4.4  3.0  1.3  0.2     Iris-setosa        11
8    4.4  2.9  1.4  0.2     Iris-setosa        11
13   4.3  3.0  1.1  0.1     Iris-setosa        11

[150 rows x 6 columns]

In [30]:
# to get each and every column max
data.max()

V1                     7.9
V2                     4.4
V3                     6.9
V4                     2.5
Type        Iris-virginica
Type_len                15
dtype: object

In [31]:
# to get each and every column min
data.min()

V1                  4.3
V2                  2.0
V3                  1.0
V4                  0.1
Type        Iris-setosa
Type_len             11
dtype: object

In [33]:
# each column mean
data.mean

<bound method DataFrame.mean of       V1   V2   V3   V4            Type  Type_len
0    5.1  3.5  1.4  0.2     Iris-setosa        11
1    4.9  3.0  1.4  0.2     Iris-setosa        11
2    4.7  3.2  1.3  0.2     Iris-setosa        11
3    4.6  3.1  1.5  0.2     Iris-setosa        11
4    5.0  3.6  1.4  0.2     Iris-setosa        11
..   ...  ...  ...  ...             ...       ...
145  6.7  3.0  5.2  2.3  Iris-virginica        14
146  6.3  2.5  5.0  1.9  Iris-virginica        14
147  6.5  3.0  5.2  2.0  Iris-virginica        14
148  6.2  3.4  5.4  2.3  Iris-virginica        14
149  5.9  3.0  5.1  1.8  Iris-virginica        14

[150 rows x 6 columns]>

In [36]:
# particular columns minimum value
data[['V1','V2']].min()

V1    4.3
V2    2.0
dtype: float64

In [37]:
data[['V1','V2']].max()

V1    7.9
V2    4.4
dtype: float64